const { chromium } = require('playwright');
const { spawn } = require('node:child_process');
const path = require('node:path');
const { pathToFileURL } = require('node:url');
const root = path.resolve(__dirname,'..');
const server = spawn(process.execPath,['tools/serve.cjs'],{cwd:root,stdio:'ignore'});
(async()=>{
  await new Promise(r=>setTimeout(r,700));
  const browser=await chromium.launch({headless:true});
  for(const viewport of [{width:390,height:844,name:'mobile'},{width:1440,height:900,name:'desktop'}]){
    const page=await browser.newPage({viewport}); const errors=[]; page.on('pageerror',e=>errors.push(e.message));
    await page.goto('http://127.0.0.1:4173/index.html');
    await page.locator('#eventsGrid').waitFor();
    if(await page.locator('#eventsGrid .event-card-3d').count()!==3) throw new Error('Event cards not rendered');
    await page.locator('.playlist button.track-item').first().waitFor();
    await page.locator('#playBtn').click(); await page.waitForTimeout(600);
    if (!await page.locator('#audioPlayer').evaluate(audio => audio.src.includes('/audio/') && !audio.paused)) throw new Error('Audio player failed');
    await page.locator('#playBtn').click();
    await page.screenshot({path:path.join(root,`hhbar-${viewport.name}.png`),fullPage:true});
    if (await page.locator('body').evaluate(el => el.scrollWidth > el.clientWidth)) throw new Error(`Horizontal overflow on ${viewport.name}`);
    await page.goto('http://127.0.0.1:4173/menu.html');
    if (await page.evaluate(() => performance.getEntriesByType('resource').some(entry => entry.name.includes('/kitchen/lemonade/')))) throw new Error('Hidden menu photos loaded before their category');
    await page.locator('.category-btn[data-cat="cocktails"]').click();
    await page.waitForFunction(() => performance.getEntriesByType('resource').some(entry => entry.name.includes('/kitchen/lemonade/')));
    await page.locator('#menuSearch').fill('кофе');
    if(!await page.locator('.menu-search-result').count()) throw new Error('Menu search failed');
    await page.route('**/widget.js?*', route => route.fulfill({
      contentType: 'application/javascript',
      body: `document.addEventListener('click',event=>{if(event.target.closest('.restoplace-click-open')){window.__restoplaceOpens=(window.__restoplaceOpens||0)+1;window.__restoplaceItem=new URLSearchParams(location.search).get('open_item');window.__restoplaceCount=new URLSearchParams(location.search).get('count');}});`
    }));
    await page.goto('http://127.0.0.1:4173/booking.html'); await page.locator('#guestCount').selectOption('10');
    const tableIds = await page.evaluate(() => window.HHRestoplace?.config.tableIds);
    if(tableIds?.['1'] !== '830804' || tableIds?.['15'] !== '830819' || tableIds?.['19'] !== '830823' || tableIds?.['20'] || Object.values(tableIds).includes('830818') || tableIds?.VIP !== '830890') throw new Error('RestoPlace table mapping failed');
    if(await page.locator('.table[data-table]').count() !== 20 || await page.locator('.table[data-table="20"]').count()) throw new Error('Hall table count or numbering failed');
    if(await page.locator('.table[data-capacity="2"]:visible').count()) throw new Error('Table filter failed');
    await page.locator('.table[data-table="15"]').click();
    if(await page.evaluate(() => window.__restoplaceOpens || 0)) throw new Error('Widget opened before photo preview');
    if(!await page.locator('#tablePreviewModal').evaluate(el => el.classList.contains('active'))) throw new Error('Table photo preview did not open');
    if(await page.locator('#tablePreviewTitle').innerText() !== 'Столик 15') throw new Error('Wrong table photo title');
    await page.locator('#tablePreviewImage').evaluate(image => new Promise((resolve,reject) => { if(image.complete) return image.naturalWidth ? resolve() : reject(new Error('Table photo failed')); image.onload=resolve; image.onerror=()=>reject(new Error('Table photo failed')); }));
    if(!await page.locator('#tablePreviewImage').getAttribute('src').then(src => src.endsWith('table-15.jpg'))) throw new Error('Wrong table photo');
    await page.screenshot({path:path.join(root,`hhbar-table-preview-${viewport.name}.png`)});
    await page.locator('#tablePreviewModal [data-restoplace-booking]').click();
    await page.waitForFunction(() => window.__restoplaceOpens === 1);
    if(await page.locator('#tablePreviewModal').evaluate(el => el.classList.contains('active'))) throw new Error('Photo preview blocks RestoPlace');
    if(await page.evaluate(() => window.__restoplaceItem) !== '830819') throw new Error('Specific RestoPlace table was not forwarded');
    if(await page.evaluate(() => window.__restoplaceCount) !== '10') throw new Error('RestoPlace guest count was not forwarded');
    await page.locator('#guestCount').selectOption('3');
    await page.locator('.table[data-table="14"]').focus();
    await page.keyboard.press('Enter');
    if(!await page.locator('#tablePreviewModal').evaluate(el => el.classList.contains('active'))) throw new Error('Keyboard did not open photo preview');
    await page.keyboard.press('Escape');
    if(await page.locator('#tablePreviewModal').evaluate(el => el.classList.contains('active'))) throw new Error('Escape did not close photo preview');
    if(!await page.locator('.table[data-table="14"]').evaluate(el => el === document.activeElement)) throw new Error('Focus did not return to table');
    await page.locator('.table[data-table="14"]').click();
    await page.locator('#tablePreviewModal [data-restoplace-booking]').click();
    await page.waitForFunction(() => window.__restoplaceOpens === 2);
    if(await page.evaluate(() => window.__restoplaceItem) !== '830817') throw new Error('Table 14 was not forwarded to live RestoPlace availability');
    if(await page.evaluate(() => location.search) !== '') throw new Error('Temporary booking query was not restored');
    if(!await page.locator('.table[data-table="14"]').evaluate(el => el.classList.contains('selected'))) throw new Error('Selected table state failed');
    await page.locator('.table[data-table="8"]').click();
    if(!await page.locator('#tablePreviewImage').getAttribute('src').then(src => src.endsWith('table-8.jpg'))) throw new Error('Table 8 photo mismatch');
    await page.locator('#tablePreviewModal [data-restoplace-booking]').click();
    await page.waitForFunction(() => window.__restoplaceOpens === 3);
    if(await page.evaluate(() => window.__restoplaceItem) !== '830811') throw new Error('Table 8 booking ID mismatch');
    await page.locator('.table[data-table="VIP"]').click();
    if(!await page.locator('#tablePreviewImage').getAttribute('src').then(src => src.endsWith('table-vip.jpg'))) throw new Error('VIP photo mismatch');
    await page.locator('#tablePreviewModal [data-restoplace-booking]').click();
    await page.waitForFunction(() => window.__restoplaceOpens === 4);
    if(await page.evaluate(() => window.__restoplaceItem) !== '830890') throw new Error('VIP booking ID mismatch');
    if(await page.locator('body').evaluate(el => el.scrollWidth > el.clientWidth)) throw new Error(`Booking overflow on ${viewport.name}`);
    await page.screenshot({path:path.join(root,`hhbar-booking-${viewport.name}.png`),fullPage:true});
    if(errors.length) throw new Error(errors.join('; '));
  }
  const localPage=await browser.newPage({viewport:{width:1440,height:900}}); const localErrors=[]; localPage.on('pageerror',e=>localErrors.push(e.message));
  await localPage.goto(pathToFileURL(path.join(root,'index.html')).href,{waitUntil:'domcontentloaded'});
  await localPage.locator('#eventsGrid .event-card-3d').first().waitFor();
  if(await localPage.locator('#eventsGrid .event-card-3d').count()!==3) throw new Error('Local-file events failed');
  await localPage.waitForFunction(() => [...document.querySelectorAll('.card-front')].every(card => {
    const match = getComputedStyle(card).backgroundImage.match(/url\(["']?(.*?)["']?\)/);
    if (!match) return false;
    const image = new Image(); image.src = match[1];
    return image.complete && image.naturalWidth > 0;
  }));
  await localPage.locator('.playlist button.track-item').first().waitFor();
  if(await localPage.locator('.playlist button.track-item').count()<3) throw new Error('Local-file music library failed');
  if(localErrors.length) throw new Error(`Local-file errors: ${localErrors.join('; ')}`);
  await browser.close(); server.kill(); console.log('Browser checks passed; screenshots created.');
})().catch(error=>{server.kill();console.error(error);process.exit(1);});
